version: '3.8'
services:
  sales-service:
    build:
      context: ./backend
      dockerfile: ./DeveloperStore.Sales/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__MongoDB=mongodb://admin:admin@123@mongo:27017
  
  api-service:
    build: 
      context: ./backend
      dockerfile: ./DeveloperStore.Api/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ConnectionStrings__PostgreSQL=Host=postgres;Database=api_service;Username=admin;Password=password
  
  gateway-service:
    build: 
      context: ./backend
      dockerfile: ./DeveloperStore.Gateway/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - sales-service
      - api-service

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin@123

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
      - POSTGRES_DB=developer_store_api_service
